### ISSUE TITLE
Angular app fails if "views/templates" folder is empty.

### ISSUE THREAD

**Issue by Krxtopher** [resource/angular-starterkit#6]
The compiled "templates.js" file does not get created if the "views/templates" folder is empty. As a result, when the app is run in the browser it throws JavaScript errors which prevent the app from running properly.

**Comment by mcgaryes** [comment]
Now up to the user to specify which views to compile in the build-config. No longer assuming the views are contained within a 'templates' directory, or any directory for that matter.
